#!/bin/bash
# NEXTFLOW TASK: associationTest (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /home/wpearse/Documents/Nextflow/work/f8/ad30568fd97af285f83f3c20c84295/.exitcode
  set +u
  [[ "$COUT" ]] && rm -f "$COUT" || true
  [[ "$CERR" ]] && rm -f "$CERR" || true
  rm -rf $NXF_SCRATCH || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

NXF_SCRATCH="$(set +u; nxf_mktemp $TMPDIR)"
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /home/wpearse/Documents/Nextflow/work/f8/ad30568fd97af285f83f3c20c84295/.command.begin
[ -f /home/wpearse/Documents/Nextflow/work/f8/ad30568fd97af285f83f3c20c84295/.command.env ] && source /home/wpearse/Documents/Nextflow/work/f8/ad30568fd97af285f83f3c20c84295/.command.env
[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
rm -f cleaned.bed
rm -f cleaned.bim
rm -f cleaned.fam
ln -s /home/wpearse/Documents/Nextflow/input/hapmap1.bed cleaned.bed
ln -s /home/wpearse/Documents/Nextflow/input/hapmap1.bim cleaned.bim
ln -s /home/wpearse/Documents/Nextflow/input/hapmap1.fam cleaned.fam


set +e
COUT=$PWD/.command.po; mkfifo "$COUT"
CERR=$PWD/.command.pe; mkfifo "$CERR"
tee .command.out < "$COUT" &
tee1=$!
tee .command.err < "$CERR" >&2 &
tee2=$!
(
/bin/bash -ue /home/wpearse/Documents/Nextflow/work/f8/ad30568fd97af285f83f3c20c84295/.command.sh
) >"$COUT" 2>"$CERR" &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
cp .command.out /home/wpearse/Documents/Nextflow/work/f8/ad30568fd97af285f83f3c20c84295 || true
cp .command.err /home/wpearse/Documents/Nextflow/work/f8/ad30568fd97af285f83f3c20c84295 || true

mkdir -p /home/wpearse/Documents/Nextflow/work/f8/ad30568fd97af285f83f3c20c84295
cp -fRL association.assoc /home/wpearse/Documents/Nextflow/work/f8/ad30568fd97af285f83f3c20c84295 || true
